spring:
  datasource:
    url: jdbc:mysql://localhost:3306/zwe-api?nullCatalogMeansCurrent=true
    username: root
    password: root

  redis:
    host: localhost
    port: 6379
    database: 1

  data:
    mongodb:
      host: localhost
      port: 27017
      database: web-api

  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1

  # 外部文件配置rabbitmq(rabbitmq 基本配置)
#  rabbitmq:
#    addresses: localhost
#    port: 5672
#    username: guest
#    password: guest
#    virtual-host: /zwe-api
#    connection-timeout: 15000 # 超时时间
#    # 消费端配置
#    listener:
#      simple:
#        concurrency: 5 #最大并发
#        acknowledge-mode: manual # 手工签收
#        max-concurrency: 10 # 最大并发数
#        prefetch: 1 # 限流，同一时间只能有一条消息过来




mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  type-aliases-package: top.zwsave.zweapi.db.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true


zwe-api: # 自定义
  secret: ILOVEZW1314 # 密钥自定义
  expire: 5 # 过期时间
  cache-expire: 10 # 缓存过期时间

## mybatis打印日志配置
#logging:
#  level:
#    root: info
#    com.example.emos.wx.db.dao: warn # 打印级别 ： 不打印繁琐文件
#  pattern:
#    console: "%d{HH:mm:ss}  %-5level  %msg%n"

tencent:
  secretId: AKIDUosfBWZNwGJ6crqYzA4h27vSihPr53lC
  secretKey: B5i8H9j36sNcaHhqjKehTyC9qFNEn68t
  bucket: zwe-api-1258360747
  regionName: ap-beijing
  baseUrl: https://zwe-api-1258360747.cos.ap-beijing.myqcloud.com