#第一行注释



spring:
  datasource:
    url: jdbc:mysql://rm-uf61x8j5l91x6190zpo.mysql.rds.aliyuncs.com/zwe?nullCatalogMeansCurrent=true
    username: zwe
    password: Zwe12345

  redis:
    host: r-uf69l1xfrvq6d5pe2mpd.redis.rds.aliyuncs.com
    port: 6379
    database: 1
    password: Redis123

  data:
    mongodb:
      host: localhost
      port: 27017
      database: web-api
#      username: zwe
#      password: Zwe12345

  rabbitmq:
    addresses: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /zwe-api
    connection-timeout: 15000 # 超时时间
    # 消费端配置
    listener:
      simple:
        concurrency: 5 #最大并发
        acknowledge-mode: manual # 手工签收
        max-concurrency: 10 # 最大并发数
        prefetch: 1 # 限流，同一时间只能有一条消息过来

server:
  port: 8280
